### ISSUE TITLE
Wi-Fi SSID with spaces

### ISSUE THREAD

**Issue by ACXgit** [RuneAudio/RuneUI#23]
http://www.runeaudio.com/forum/runeaudio-0-3-alpha-for-raspberry-pi-t309-290.html#p2479

**Comment by kdubious** [comment]
Made a pull request containing the fix. Would like to discuss with a team member who is confident with the `runeaudio.php` file.

**Comment by ACXgit** [comment]
Solved in the dev branch, coming on the main for 0.4 release.
