### ISSUE TITLE
"Add, replace and play" glitch

### ISSUE THREAD

**Issue by ACXgit** [RuneAudio/RuneUI#39]
"Add, replace and play" command does not trigger a UI update - quickly visible starting from a 'pause' or 'stop' state.

**Comment by kdubious** [comment]
Try wrapping the three individual calls in "command_list_begin" ... "command_list_end"

**Comment by ACXgit** [comment]
Fixed https://github.com/RuneAudio/RuneUI/commit/5c5c4d13939e33d4b75c17b1ef3a6835ae3969aa, thank you @kdubious for the tip!
