### ISSUE TITLE
WebUI puts netmask wrong in netctl file for eth0 when changing to static ip

### ISSUE THREAD

**Issue by schwermie** [RuneAudio/RuneUI#48]
After setting the eth0 IP settings to static. The netmask is not put as CIDR notation. 
This results in a unavailable network after reboot.

Address=('192.168.1.11/255.255.255.0')

Must be:

Address('192.168.1.11/24')

**Comment by ACXgit** [comment]
Solved in the dev branch, coming on the main for 0.4 release.
