### ISSUE TITLE
Player selection confusing

### ISSUE THREAD

**Issue by mattbrailsford** [RuneAudio/RuneUI#53]
This is my first time playing with Rune so I just thought I'd share the confusion I had with the player selector.

I grasp that things like spotify / airplay can't work in combination with the standard built MPD player, so I get why you need to change the active player, although I do find how you change this confusing. Right now, the only place you seem to be able to do that is on the playback screen, mixed in with the track information. Clicking a small label brings up the player select dialog for you to change the active player. I think this needs to be a lot more obvious.

The other issue I had was that originally I was using MPD and spotify showed up in my library section, but clicking spotify auto selected the spotify player, and then disabled all the other library options. I was therefore not able to switch to my local media library without going to the playback screen and choosing the default MPD player (which I originally didn't know this so was lost with no help till I found it). Another thing I found confusing is that in the library section, the spotify block refers to the player as a "renderer" where as it's a player elsewhere, so maybe this needs making consistent.

If certain libraries can only be used in the context of certain players, and they can't be intermingled (ie I can't queue up and MPD track followed by a spotify track) I think the selecting of a player needs to be much more obvious and I think the library section should only show what is relevant for that player. Given that the whole player UI (library, playback and queue) is all specific to the active player, I think the selection of a player needs to be portrayed in a global way. Maybe within the top right menu (though this still feels a bit hidden) or maybe by some new button visible in the UI at all times and easily clickable to switch the player.

**Comment by ACXgit** [comment]
Hi Matt, from your description it seems that you are not using the very latest version of RuneAudio - seems like you are using 0.3-beta but without the git updates. So take a look here:
http://www.runeaudio.com/documentation/troubleshooting/updating/
as most of the issues you describe have already been solved or at least limited via updates.

**Comment by mattbrailsford** [comment]
Ahh, yes. I was just using the beta. Didn't realise there were extra
updates. I'll update everything and test again.
