### ISSUE TITLE
Attaching hard drive crashes server

### ISSUE THREAD

**Issue by jrosseel** [RuneAudio/RuneUI#58]
Hi,

I have a 2TB Hard Drive with only 200GB of Music on it. Every time that I connect the Hard Drive. The system starts scanning it for music rendering everything else broken. Without attaching the hard drive everything works fine.

Is it possible to introduce a feature that allows you to search only certain folders of your HDD or maybe to load the HDD asynchronously with the web server and keep adding music to the library as the files are discovered? Then you could already listen to some music while the rest is still loading. Or some progress bar of sort would also be nice.

**Comment by ACXgit** [comment]
Hi @jrosseel, what do you mean exactly with "rendering everything else broken"?
You can exclude folders from being scanned simply dropping a file named as .mpdignore inside them.

**Comment by jrosseel** [comment]
Hi Andrea,

Thanks for the fast reply. I meant the webserver became unresponsive. I
couldn't connect to it anymore nor did the device play music. Thanks for
the tip, I'll try adding the .mdpignore.

Op vr 10 apr. 2015 om 16:02 schreef Andrea Coiutti <notifications@github.com

**Comment by jrosseel** [comment]
I added the .mdpignore tags to all the folders that don't need scanning but the system is still unresponsive while scanning th rest of the folders. I connected the Hard Drive half an hour ago and I still can't make a connection with the web server. Their is 160GB of music combined in the folders that don't contain .mdpignore.

**Comment by ACXgit** [comment]
A MPD library update shouldn't take so long, even with huge collections, and more important it shouldn't hang the device in the process. Possible causes could be:
- corrupted files?
- problematic filenames/tags?
- PSU issues?

**Comment by jrosseel** [comment]
I'm using a HDD that is powered over USB so PSU seems most likely to be the problem. I'm copying a part of my music library to another externally powered HDD and will try with that one.

**Comment by jrosseel** [comment]
That was indeed the problem. It works now using the externally powered HDD. Thank you for your help!

**Comment by ACXgit** [comment]
You're welcome!
