### ISSUE TITLE
Add "consume" option

### ISSUE THREAD

**Issue by jostev** [RuneAudio/RuneUI#71]
It would be nice if there was a "consume" option that can be toggled (like "random").
So that songs from the queue gets consumed when played.

**Comment by ACXgit** [comment]
It was available but it has been temporarily disabled.
If you need it you can manually bring it back uncommenting this line:
https://github.com/RuneAudio/RuneUI/blob/master/app/templates/playback.php#L21
and refreshing the PHP cache after that (just point your browser to http://runeaudio.local/clear).
